Configuraciones As screen:
    Fill: =RGBA(0, 0, 0, 1)

    Label1 As label:
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Semibold
        Height: =84
        Size: =23
        Text: ="x"
        Width: =415
        X: =205
        Y: =130
        ZIndex: =2

    Label10 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =27
        Size: =21
        Text: ="ver perfil"
        Width: =435
        X: =205
        Y: =220
        ZIndex: =3

    Icon9 As icon.ChevronRight:
        BorderColor: =RGBA(172, 0, 255, 1)
        Color: =RGBA(172, 0, 255, 1)
        Height: =40
        Icon: =Icon.ChevronRight
        Width: =37
        X: =511
        Y: =152
        ZIndex: =4

    Label13 As label:
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Semibold
        Height: =44
        Size: =21
        Text: ="Cuenta"
        Width: =560
        X: =51
        Y: =275
        ZIndex: =5

    Label14 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =54
        Size: =21
        Text: ="Email"
        Width: =560
        X: =51
        Y: =319
        ZIndex: =6

    Label15 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =31
        Size: =21
        Text: ="x"
        Width: =509
        X: =51
        Y: =373
        ZIndex: =7

    Label16 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =51
        Size: =21
        Text: ="Usuario"
        Width: =560
        X: =51
        Y: =406
        ZIndex: =8

    Label15_1 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =31
        Size: =21
        Text: ="x"
        Width: =509
        X: =51
        Y: =464
        ZIndex: =9

    Label16_1 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =51
        Size: =21
        Text: ="Contraseña"
        Width: =560
        X: =51
        Y: =500
        ZIndex: =10

    Label15_2 As label:
        Color: =RGBA(255, 255, 255, 1)
        Height: =31
        Size: =21
        Text: ="x"
        Width: =509
        X: =51
        Y: =551
        ZIndex: =11

    TextInput1_11 As text:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =0
        Color: =RGBA(15, 15, 15, 1)
        Default: =""
        DisabledBorderColor: =RGBA(172, 0, 255, 1)
        DisabledFill: =RGBA(172, 0, 255, 1)
        Height: =10
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =640
        Y: =1008
        ZIndex: =12

    TextInput1_12 As text:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =0
        Color: =RGBA(15, 15, 15, 1)
        Default: =""
        DisabledBorderColor: =RGBA(172, 0, 255, 1)
        DisabledFill: =RGBA(172, 0, 255, 1)
        Height: =10
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =640
        Y: =90
        ZIndex: =13

    Label1_7 As label:
        Color: =RGBA(172, 0, 255, 1)
        Height: =64
        Size: =21
        Text: ="Tu libreria"
        Width: =153
        X: =407
        Y: =1072
        ZIndex: =14

    Icon2_3 As icon.Home:
        Color: =RGBA(172, 0, 255, 1)
        Icon: =Icon.Home
        X: =91
        Y: =1022
        ZIndex: =15

    Icon5_3 As icon.DetailList:
        Color: =RGBA(172, 0, 255, 1)
        Height: =71
        Icon: =Icon.DetailList
        Width: =56
        X: =455
        Y: =1018
        ZIndex: =16

    Icon6_3 As icon.Search:
        Color: =RGBA(172, 0, 255, 1)
        Icon: =Icon.Search
        X: =265
        Y: =1022
        ZIndex: =17

    Label4_4 As label:
        Color: =RGBA(172, 0, 255, 1)
        Height: =64
        Size: =21
        Text: ="Home"
        Width: =94
        X: =76
        Y: =1072
        ZIndex: =18

    Label5_4 As label:
        Color: =RGBA(172, 0, 255, 1)
        Height: =64
        Size: =21
        Text: ="Buscar"
        Width: =125
        X: =254
        Y: =1072
        ZIndex: =19

