Configuraciones As screen:
    Fill: =RGBA(0, 0, 0, 1)
    LoadingSpinnerColor: =RGBA(197, 24, 128, 1)

    Label1 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Semibold
        Height: =57
        Size: =23
        Text: ="x"
        Width: =316
        X: =195
        Y: =238
        ZIndex: =1

    Label10 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =27
        Size: =21
        Text: ="ver perfil"
        Width: =435
        X: =195
        Y: =295
        ZIndex: =2

    Icon9 As icon.ChevronRight:
        BorderColor: =RGBA(172, 0, 255, 1)
        Color: =RGBA(172, 0, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =40
        Icon: =Icon.ChevronRight
        Width: =37
        X: =491
        Y: =238
        ZIndex: =3

    Label13 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Semibold
        Height: =44
        Size: =21
        Text: ="Cuenta"
        Width: =560
        X: =51
        Y: =356
        ZIndex: =4

    Label14 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =54
        Size: =21
        Text: ="Email"
        Width: =560
        X: =32
        Y: =400
        ZIndex: =5

    Label15 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =31
        Size: =21
        Text: ="x"
        Width: =509
        X: =51
        Y: =466
        ZIndex: =6

    Label16 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =51
        Size: =21
        Text: ="Usuario"
        Width: =560
        X: =36
        Y: =502
        ZIndex: =7

    Label15_1 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =31
        Size: =21
        Text: ="x"
        Width: =509
        X: =51
        Y: =559
        ZIndex: =8

    Label16_1 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =51
        Size: =21
        Text: ="Contraseña"
        Width: =560
        X: =36
        Y: =590
        ZIndex: =9

    Label15_2 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =31
        Size: =21
        Text: ="x"
        Width: =509
        X: =51
        Y: =641
        ZIndex: =10

    TextInput1_11 As text:
        BorderThickness: =0
        Color: =RGBA(15, 15, 15, 1)
        Default: =""
        DisabledBorderColor: =RGBA(172, 0, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(172, 0, 255, 1)
        FocusedBorderThickness: =4
        Height: =10
        HoverBorderColor: =RGBA(189, 189, 189, 1)
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =RGBA(108, 8, 68, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =21
        Width: =640
        Y: =1008
        ZIndex: =11

    Image6 As image:
        BorderColor: =RGBA(189, 189, 189, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Height: =105
        Width: =165
        X: =40
        Y: =238
        ZIndex: =19

    Rectangle7 As rectangle:
        BorderColor: =RGBA(104, 0, 156, 1)
        Fill: =RGBA(104, 0, 156, 1)
        Height: =68
        Width: =640
        Y: =100
        ZIndex: =20

    Label17 As label:
        BorderColor: =RGBA(189, 189, 189, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Semibold
        Height: =70
        Size: =21
        Text: ="Configuraciones"
        Width: =367
        X: =205
        Y: =98
        ZIndex: =21

    Icon10 As icon.ChevronLeft:
        BorderColor: =RGBA(172, 0, 255, 1)
        Color: =RGBA(172, 0, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =40
        Icon: =Icon.ChevronLeft
        Width: =59
        X: =32
        Y: =113
        ZIndex: =22

    Group9_32 As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =29

        Label1_37 As label:
            Align: =Align.Center
            BorderColor: =RGBA(189, 189, 189, 1)
            Color: =RGBA(172, 0, 255, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            Height: =64
            OnSelect: =Navigate(Libreria)
            Size: =21
            Text: ="Libreria"
            Width: =153
            X: =240
            Y: =1072
            ZIndex: =23

        Icon5_33 As icon.DetailList:
            BorderColor: =RGBA(189, 189, 189, 1)
            Color: =RGBA(172, 0, 255, 1)
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledColor: =RGBA(244, 244, 244, 1)
            Height: =71
            Icon: =Icon.DetailList
            OnSelect: =Navigate(Libreria)
            Width: =56
            X: =288
            Y: =1021
            ZIndex: =26

    Group8_32 As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =30

        Icon2_33 As icon.Home:
            BorderColor: =RGBA(189, 189, 189, 1)
            Color: =RGBA(172, 0, 255, 1)
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledColor: =RGBA(244, 244, 244, 1)
            Icon: =Icon.Home
            OnSelect: =Navigate(Home)
            X: =80
            Y: =1025
            ZIndex: =25

        Label4_34 As label:
            BorderColor: =RGBA(189, 189, 189, 1)
            Color: =RGBA(172, 0, 255, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            Height: =64
            OnSelect: =Navigate(Home)
            Size: =21
            Text: ="Home"
            Width: =94
            X: =68
            Y: =1072
            ZIndex: =27

    Group10_32 As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =31

        Icon1_32 As icon.Settings:
            BorderColor: =RGBA(189, 189, 189, 1)
            Color: =RGBA(255, 255, 255, 1)
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledColor: =RGBA(244, 244, 244, 1)
            Height: =52
            Icon: =Icon.Settings
            OnSelect: =Navigate(Configuraciones)
            X: =495
            Y: =1031
            ZIndex: =24

        Label5_30 As label:
            BorderColor: =RGBA(189, 189, 189, 1)
            Color: =RGBA(255, 255, 255, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            Height: =64
            OnSelect: =Navigate(Configuraciones)
            Size: =21
            Text: ="Ajustes"
            Width: =125
            X: =474
            Y: =1072
            ZIndex: =28

